-- Create crawl_stats table
CREATE TABLE IF NOT EXISTS crawl_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    community_count INTEGER,
    total_items INTEGER,
    filtered_items INTEGER,
    hotdeal_items INTEGER,
    total_savings INTEGER
);
