-- Add pgvector extension if not exists
CREATE EXTENSION IF NOT EXISTS vector;

-- Add embedding column to hotdeals table for vector search
ALTER TABLE public.hotdeals 
ADD COLUMN IF NOT EXISTS embedding vector(768);

-- Optional: Add comment for documentation
COMMENT ON COLUMN public.hotdeals.embedding IS '768-dimensional vector generated by gemini-embedding-001';
